apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: wsdemo-web
  name: wsdemo-web
  namespace: wsdemo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: wsdemo-web
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wsdemo-web
    spec:
      containers:
      - env:
        - name: NPM_SCRIPT_TO_RUN
          value: start-web
        envFrom:
        - configMapRef:
            name: wsdemo-conf
        - secretRef:
            name: wsdemo-secret
        image: 434544098537.dkr.ecr.eu-west-1.amazonaws.com/wsdemo:latest
        imagePullPolicy: IfNotPresent
        name: wsdemo
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 5858
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30