apiVersion: v1
kind: Service
metadata:
  name: wsdemo-srv
  namespace: wsdemo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: wsdemo-web
  sessionAffinity: None
  type: ClusterIP